version: '2'
services:
  database-apim_rdbms:
    build:
        context: ../
        dockerfile: pattern-9/database/Dockerfile
    environment:
        MYSQL_ROOT_PASSWORD: root
  svn-svnrepo:
    image: docker.wso2.com/svnrepo
  wso2analytics-analytics:
    build:
      context: ../
      dockerfile: pattern-9/am-analytics/Dockerfile
    environment:
      - SLEEP=30
    ports:
    - "9448:9444"
  wso2am-gateway-manager:
    build:
      context: ../
      dockerfile: pattern-9/gateway-manager/Dockerfile
    environment:
      - SLEEP=60
    ports:
    - "9444:9443"
  wso2am-keymanager-tm-gw:
    build:
      context: ../
      dockerfile: pattern-9/keymanager-tm-gw/Dockerfile
    environment:
      - SLEEP=120
    ports:
    - "9443:9443"
    - "8280:8280"
    - "8243:8243"
  wso2am-store:
    build:
      context: ../
      dockerfile: pattern-9/store/Dockerfile
    environment:
      - SLEEP=200
    ports:
    - "9446:9443"
  wso2am-publisher:
    build:
      context: ../
      dockerfile: pattern-9/publisher/Dockerfile
    environment:
      - SLEEP=200
    ports:
      - "9445:9443"