version: '2'
services:
  database-apim_rdbms:
    build:
        context: ../
        dockerfile: pattern-1/database/Dockerfile
    environment:
        MYSQL_ROOT_PASSWORD: root
  wso2am-api-manager:
    build:
      context: ../
      dockerfile: pattern-1/api-manager/Dockerfile
    environment:
      - SLEEP=10
    ports:
      - "443:9443"
      - "80:9763"
      - "8280:8280"
      - "8243:8243"
