version: '2'
services:
  apim_rdbms:
    image: docker.wso2.com/swarm-apim-pattern1-mysql:5.5
    build:
        context: ../
        dockerfile: pattern-1/database/Dockerfile
    environment:
        MYSQL_ROOT_PASSWORD: root
  api-manager:
    image: docker.wso2.com/swarm-apim-pattern1-wso2am:2.0.0
    build:
      context: ../
      dockerfile: pattern-1/api-manager/Dockerfile
    environment:
       SLEEP: 20
