version: '2'
services:
  apim_rdbms:
    image: docker.wso2.com/swarm-apim-pattern6-mysql:5.5
    build:
        context: ../
        dockerfile: pattern-6/database/Dockerfile
    environment:
        MYSQL_ROOT_PASSWORD: root
  svnrepo:
    image: docker.wso2.com/svnrepo
  analytics:
    image: docker.wso2.com/swarm-apim-pattern6-wso2am-analytics:2.0.0
    build:
      context: ../
      dockerfile: pattern-6/am-analytics/Dockerfile
    environment:
      - SLEEP=5
    ports:
    - "9448:9444"
  traffic-manager:
    image: docker.wso2.com/swarm-apim-pattern6-traffic-manager:2.0.0
    build:
      context: ../
      dockerfile: pattern-6/traffic-manager/Dockerfile
    environment:
      - SLEEP=5
    ports:
    - "9447:9443"
  keymanager:
    image: docker.wso2.com/swarm-apim-pattern6-keymanager:2.0.0
    build:
      context: ../
      dockerfile: pattern-6/keymanager/Dockerfile
    environment:
      - SLEEP=60
    ports:
    - "9443:9443"
  gateway-manager:
    image: docker.wso2.com/swarm-apim-pattern6-gateway-manager:2.0.0
    build:
      context: ../
      dockerfile: pattern-6/gateway-manager/Dockerfile
    environment:
      - SLEEP=100
    ports:
    - "9444:9443"
  gateway-worker:
    image: docker.wso2.com/swarm-apim-pattern6-gateway-worker:2.0.0
    build:
      context: ../
      dockerfile: pattern-6/gateway-worker/Dockerfile
    environment:
      - SLEEP=180
    ports:
    - "8280:8280"
    - "8243:8243"
  publisher-store:
    image: docker.wso2.com/swarm-apim-pattern6-publisher-store:2.0.0
    build:
      context: ../
      dockerfile: pattern-6/publisher-store/Dockerfile
    environment:
      - SLEEP=200
    ports:
      - "9445:9443"