version: '2'
services:
  database-apim_rdbms:
    build:
        context: ../
        dockerfile: pattern-6/database/Dockerfile
    environment:
        MYSQL_ROOT_PASSWORD: root
  svn-svnrepo:
    image: docker.wso2.com/svnrepo
  wso2analytics-analytics:
    build:
      context: ../
      dockerfile: pattern-6/am-analytics/Dockerfile
    environment:
      - SLEEP=5
    ports:
    - "9448:9444"
  wso2am-traffic-manager:
    build:
      context: ../
      dockerfile: pattern-6/traffic-manager/Dockerfile
    environment:
      - SLEEP=5
    ports:
    - "9447:9443"
  wso2am-keymanager:
    build:
      context: ../
      dockerfile: pattern-6/keymanager/Dockerfile
    environment:
      - SLEEP=60
    ports:
    - "9443:9443"
  wso2am-gateway-manager:
    build:
      context: ../
      dockerfile: pattern-6/gateway-manager/Dockerfile
    environment:
      - SLEEP=100
    ports:
    - "9444:9443"
  wso2am-gateway-worker:
    build:
      context: ../
      dockerfile: pattern-6/gateway-worker/Dockerfile
    environment:
      - SLEEP=180
    ports:
    - "8280:8280"
    - "8243:8243"
  wso2am-publisher-store:
    build:
      context: ../
      dockerfile: pattern-6/publisher-store/Dockerfile
    environment:
      - SLEEP=200
    ports:
      - "9445:9443"