version: '2'
services:
  database-apim_rdbms:
    image: docker.wso2.com/swarm-apim-pattern3-mysql:5.5
    build:
        context: ../
        dockerfile: pattern-3/database/Dockerfile
    environment:
        MYSQL_ROOT_PASSWORD: root
  svn-svnrepo:
    image: docker.wso2.com/svnrepo
  wso2analytics-analytics:
    image: docker.wso2.com/swarm-apim-pattern3-am-analytics:2.0.0
    build:
      context: ../
      dockerfile: pattern-3/am-analytics/Dockerfile
    environment:
      - SLEEP=5
    ports:
    - "9448:9444"
  wso2am-traffic-manager:
    image: docker.wso2.com/swarm-apim-pattern3-traffic-manager:2.0.0
    build:
      context: ../
      dockerfile: pattern-3/traffic-manager/Dockerfile
    environment:
      - SLEEP=5
    ports:
    - "9447:9443"
  wso2am-keymanager:
    image: docker.wso2.com/swarm-apim-pattern3-keymanager:2.0.0
    build:
      context: ../
      dockerfile: pattern-3/keymanager/Dockerfile
    environment:
      - SLEEP=60
    ports:
    - "9443:9443"
  wso2am-gateway-manager:
    image: docker.wso2.com/swarm-apim-pattern3-gateway-manager:2.0.0
    build:
      context: ../
      dockerfile: pattern-3/gateway-manager/Dockerfile
    environment:
      - SLEEP=100
    ports:
    - "9444:9443"
  wso2am-gateway-worker:
    image: docker.wso2.com/swarm-apim-pattern3-gateway-worker:2.0.0
    build:
      context: ../
      dockerfile: pattern-3/gateway-worker/Dockerfile
    environment:
      - SLEEP=180
    ports:
    - "8280:8280"
    - "8243:8243"
  wso2am-store:
    image: docker.wso2.com/swarm-apim-pattern3-store:2.0.0
    build:
      context: ../
      dockerfile: pattern-3/store/Dockerfile
    environment:
      - SLEEP=200
    ports:
    - "9446:9443"
  wso2am-publisher:
    image: docker.wso2.com/swarm-apim-pattern3-publisher:2.0.0
    build:
      context: ../
      dockerfile: pattern-3/publisher/Dockerfile
    environment:
      - SLEEP=200
    ports:
      - "9445:9443"
