version: '2'
services:
  database-apim_rdbms:
    build:
        context: ../
        dockerfile: pattern-7/database/Dockerfile
    environment:
        MYSQL_ROOT_PASSWORD: root
  svn-svnrepo:
    image: docker.wso2.com/svnrepo
  wso2analytics-analytics:
    build:
      context: ../
      dockerfile: pattern-7/am-analytics/Dockerfile
    environment:
      - SLEEP=5
    ports:
    - "9448:9444"
  wso2am-traffic-manager:
    build:
      context: ../
      dockerfile: pattern-7/traffic-manager/Dockerfile
    environment:
      - SLEEP=5
    ports:
    - "9447:9443"
  wso2am-gateway-manager:
    build:
      context: ../
      dockerfile: pattern-7/gateway-manager/Dockerfile
    environment:
      - SLEEP=100
    ports:
    - "9444:9443"
  wso2am-gateway-worker-km:
    build:
      context: ../
      dockerfile: pattern-7/gateway-worker-km/Dockerfile
    environment:
      - SLEEP=180
    ports:
    - "9443:9443"
    - "8280:8280"
    - "8243:8243"
  wso2am-store:
    build:
      context: ../
      dockerfile: pattern-7/store/Dockerfile
    environment:
      - SLEEP=200
    ports:
    - "9446:9443"
  wso2am-publisher:
    build:
      context: ../
      dockerfile: pattern-7/publisher/Dockerfile
    environment:
      - SLEEP=240
    ports:
      - "9445:9443"
