version: '2'
services:
  apim_rdbms:
    build:
        context: ../
        dockerfile: pattern-3/database/Dockerfile
    environment:
        MYSQL_ROOT_PASSWORD: root
  svnrepo:
    image: dockerhub.private.wso2.com/svnrepo
  svnrepo-lan2:
    image: dockerhub.private.wso2.com/svnrepo
  analytics:
    build:
      context: ../
      dockerfile: pattern-3/am-analytics/Dockerfile
    environment:
      - SLEEP=5
    ports:
    - "9448:9444"
  traffic-manager:
    build:
      context: ../
      dockerfile: pattern-3/traffic-manager/Dockerfile
    environment:
      - SLEEP=5
    ports:
    - "9447:9443"
  keymanager:
    build:
      context: ../
      dockerfile: pattern-3/keymanager/Dockerfile
    environment:
      - SLEEP=60
    ports:
    - "9443:9443"
  gateway-manager:
    build:
      context: ../
      dockerfile: pattern-3/gateway-manager/Dockerfile
    environment:
      - SLEEP=100
    ports:
    - "9444:9443"
  gateway-worker:
    build:
      context: ../
      dockerfile: pattern-3/gateway-worker/Dockerfile
    environment:
      - SLEEP=180
    ports:
    - "8280:8280"
    - "8243:8243"
  store:
    build:
      context: ../
      dockerfile: pattern-3/store/Dockerfile
    environment:
      - SLEEP=200
    ports:
    - "9446:9443"
  gateway-manager-lan2:
    build:
      context: ../
      dockerfile: pattern-3/gateway-manager-lan2/Dockerfile
    environment:
      - SLEEP=100
    ports:
    - "9449:9443"
  gateway-worker-lan2:
    build:
      context: ../
      dockerfile: pattern-3/gateway-worker-lan2/Dockerfile
    environment:
      - SLEEP=180
    ports:
    - "8281:8280"
    - "8244:8243"
  publisher:
    build:
      context: ../
      dockerfile: pattern-3/publisher/Dockerfile
    environment:
      - SLEEP=200
    ports:
      - "9445:9443"
  nginx:
    build:
      context: ../
      dockerfile: pattern-3/nginx/Dockerfile
    environment:
      - SLEEP=60
    ports:
      - "443:9443"
      - "80:9763"
#  nginx-lan2:
#    build:
#      context: ../
#      dockerfile: pattern-3/nginx-lan2/Dockerfile
#    environment:
#      - SLEEP=60
#    ports:
#      - "9445:9443"
#      - "9765:9763"
