version: '2'
services:
  apim_rdbms:
    image: docker.wso2.com/swarm-apim-pattern8-mysql:5.5
    build:
        context: ../
        dockerfile: pattern-8/database/Dockerfile
    environment:
        MYSQL_ROOT_PASSWORD: root
  svnrepo:
    image: docker.wso2.com/svnrepo
  analytics:
    image: docker.wso2.com/apim-pattern8-wso2am-analytics:2.0.0
    build:
      context: ../
      dockerfile: pattern-8/am-analytics/Dockerfile
    environment:
      - SLEEP=5
    ports:
    - "9448:9444"
  keymanager-tm:
    image: docker.wso2.com/apim-pattern8-keymanager-tm:2.0.0
    build:
      context: ../
      dockerfile: pattern-8/keymanager-tm/Dockerfile
    environment:
      - SLEEP=60
    ports:
    - "9443:9443"
  gateway-manager:
    image: docker.wso2.com/apim-pattern8-gateway-manager:2.0.0
    build:
      context: ../
      dockerfile: pattern-8/gateway-manager/Dockerfile
    environment:
      - SLEEP=100
    ports:
    - "9444:9443"
  gateway-worker:
    image: docker.wso2.com/apim-pattern8-gateway-worker:2.0.0
    build:
      context: ../
      dockerfile: pattern-8/gateway-worker/Dockerfile
    environment:
      - SLEEP=180
    ports:
    - "8280:8280"
    - "8243:8243"
  store:
    image: docker.wso2.com/apim-pattern8-store:2.0.0
    build:
      context: ../
      dockerfile: pattern-8/store/Dockerfile
    environment:
      - SLEEP=200
    ports:
    - "9446:9443"
  publisher:
    image: docker.wso2.com/apim-pattern8-publisher:2.0.0
    build:
      context: ../
      dockerfile: pattern-8/publisher/Dockerfile
    environment:
      - SLEEP=200
    ports:
      - "9445:9443"