version: '2'
services:
  apim_rdbms:
    image: dockerhub.private.wso2.com/apim-pattern2-mysql:5.5
    build:
        context: ../
        dockerfile: pattern-4/database/Dockerfile
    environment:
        MYSQL_ROOT_PASSWORD: root
  svnrepo:
    image: dockerhub.private.wso2.com/svnrepo
  analytics:
    image: dockerhub.private.wso2.com/apim-pattern6-wso2am-analytics:2.0.0
    build:
      context: ../
      dockerfile: pattern-4/am-analytics/Dockerfile
    environment:
      - SLEEP=5
    ports:
    - "9448:9444"
#  traffic-manager:
#    image: dockerhub.private.wso2.com/apim-pattern6-traffic-manager:2.0.0
#    build:
#      context: ../
#      dockerfile: pattern-4/traffic-manager/Dockerfile
#    environment:
#      - SLEEP=5
#    ports:
#    - "9447:9443"
  gateway-manager:
    image: dockerhub.private.wso2.com/apim-pattern6-gateway-manager:2.0.0
    build:
      context: ../
      dockerfile: pattern-4/gateway-manager/Dockerfile
    environment:
      - SLEEP=100
    ports:
    - "9444:9443"
  gateway-worker-km:
    image: dockerhub.private.wso2.com/apim-pattern6-gateway-worker-km:2.0.0
    build:
      context: ../
      dockerfile: pattern-4/gateway-worker-km/Dockerfile
    environment:
      - SLEEP=180
    ports:
    - "9443:9443"
    - "8280:8280"
    - "8243:8243"
  store:
    image: dockerhub.private.wso2.com/apim-pattern6-store:2.0.0
    build:
      context: ../
      dockerfile: pattern-4/store/Dockerfile
    environment:
      - SLEEP=200
    ports:
    - "9446:9443"
  publisher-tm:
    image: dockerhub.private.wso2.com/apim-pattern6-publisher:2.0.0
    build:
      context: ../
      dockerfile: pattern-4/publisher/Dockerfile
    environment:
      - SLEEP=240
    ports:
      - "9445:9443"