version: '2'
services:
  apim_rdbms:
    image: docker.wso2.com/swarm-apim-pattern9-mysql:5.5
    build:
        context: ../
        dockerfile: pattern-9/database/Dockerfile
    environment:
        MYSQL_ROOT_PASSWORD: root
  svnrepo:
    image: docker.wso2.com/svnrepo
  analytics:
    image: docker.wso2.com/swarm-apim-pattern9-wso2am-analytics:2.0.0
    build:
      context: ../
      dockerfile: pattern-9/am-analytics/Dockerfile
    environment:
      - SLEEP=5
    ports:
    - "9448:9444"
  keymanager-tm-gw:
    image: docker.wso2.com/swarm-apim-pattern9-keymanager-tm-gw:2.0.0
    build:
      context: ../
      dockerfile: pattern-9/keymanager-tm-gw/Dockerfile
    environment:
      - SLEEP=120
    ports:
    - "9443:9443"
    - "8280:8280"
    - "8243:8243"
  gateway-manager:
    image: docker.wso2.com/swarm-apim-pattern9-gateway-manager:2.0.0
    build:
      context: ../
      dockerfile: pattern-9/gateway-manager/Dockerfile
    environment:
      - SLEEP=60
    ports:
    - "9444:9443"
  store:
    image: docker.wso2.com/swarm-apim-pattern9-store:2.0.0
    build:
      context: ../
      dockerfile: pattern-9/store/Dockerfile
    environment:
      - SLEEP=200
    ports:
    - "9446:9443"
  publisher:
    image: docker.wso2.com/swarm-apim-pattern9-publisher:2.0.0
    build:
      context: ../
      dockerfile: pattern-9/publisher/Dockerfile
    environment:
      - SLEEP=200
    ports:
      - "9445:9443"