version: '2'
services:
  apim_rdbms:
    image: dockerhub.private.wso2.com/apim-pattern3-mysql:5.5
    build:
        context: ../
        dockerfile: pattern-3/database/Dockerfile
    environment:
        MYSQL_ROOT_PASSWORD: root
  svnrepo:
    image: dockerhub.private.wso2.com/svnrepo
  svnrepo-lan2:
    image: dockerhub.private.wso2.com/svnrepo
  analytics:
    image: dockerhub.private.wso2.com/apim-pattern3-wso2am-analytics:2.0.0
    build:
      context: ../
      dockerfile: pattern-3/am-analytics/Dockerfile
    environment:
      - SLEEP=5
    ports:
    - "9448:9444"
  traffic-manager:
    image: dockerhub.private.wso2.com/apim-pattern3-traffic-manager:2.0.0
    build:
      context: ../
      dockerfile: pattern-3/traffic-manager/Dockerfile
    environment:
      - SLEEP=5
    ports:
    - "9447:9443"
  keymanager:
    image: dockerhub.private.wso2.com/apim-pattern3-keymanager:2.0.0
    build:
      context: ../
      dockerfile: pattern-3/keymanager/Dockerfile
    environment:
      - SLEEP=60
    ports:
    - "9443:9443"
  gateway-manager:
    image: dockerhub.private.wso2.com/apim-pattern3-gateway-manager:2.0.0
    build:
      context: ../
      dockerfile: pattern-3/gateway-manager/Dockerfile
    environment:
      - SLEEP=100
    ports:
    - "9444:9443"
  gateway-worker:
    image: dockerhub.private.wso2.com/apim-pattern3-gateway-worker:2.0.0
    build:
      context: ../
      dockerfile: pattern-3/gateway-worker/Dockerfile
    environment:
      - SLEEP=180
    ports:
    - "8280:8280"
    - "8243:8243"
  store:
    image: dockerhub.private.wso2.com/apim-pattern3-store:2.0.0
    build:
      context: ../
      dockerfile: pattern-3/store/Dockerfile
    environment:
      - SLEEP=200
    ports:
    - "9446:9443"
  gateway-manager-lan2:
    image: dockerhub.private.wso2.com/apim-pattern3-gateway-manager-lan2:2.0.0
    build:
      context: ../
      dockerfile: pattern-3/gateway-manager-lan2/Dockerfile
    environment:
      - SLEEP=100
    ports:
    - "9449:9443"
  gateway-worker-lan2:
    image: dockerhub.private.wso2.com/apim-pattern3-gateway-worker-lan2:2.0.0
    build:
      context: ../
      dockerfile: pattern-3/gateway-worker-lan2/Dockerfile
    environment:
      - SLEEP=180
    ports:
    - "8281:8280"
    - "8244:8243"
  publisher:
    image: dockerhub.private.wso2.com/apim-pattern3-publisher:2.0.0
    build:
      context: ../
      dockerfile: pattern-3/publisher/Dockerfile
    environment:
      - SLEEP=200
    ports:
      - "9445:9443"